apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "springboot-test"
  description: "A test component for Spring Boot"
  annotations:
    github.com/project-slug: "peterhmjacobsorg/springboot-test"
    backstage.io/techdocs-ref: github:https://github.com/peterhmjacobsorg/springboot-test
  tags:
    - java
spec:
  type: service
  lifecycle: production
  owner: "peterhmjacobs"
